version: '3.5'

services:
  backend:
    image: ghcr.io/unizar-30226-2021-03/backend/keypax-backcontainer:stable 
    networks:
      - backend
    environment:
      - ACCESS_TOKEN=${access_token}
      - VERIFICATION_TOKEN=${verification_token}
      - DB_CONN=mongodb+srv://KeyPaXAdmin:${password}@cluster0.yyh5k.mongodb.net/KeyPax?retryWrites=true&w=majority
      - PORT=8080
      - USER_EMAIL=${email}
      - USER_PASSWORD=${password}
      - MASTER_SALT=${master_salt}
  nginx-proxy:
    image: ghcr.io/unizar-30226-2021-03/backend/nginx-container:stable 
    environment:
      - CERTBOT_EMAIL=${email}
    volumes:
      - nginx_secrets:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - backend  
networks:
  backend:
    driver: bridge
volumes:
  nginx_secrets: